### ISSUE TITLE
giving error in windows while running

### ISSUE THREAD

**Issue by makkulkarni** [GeoscienceAustralia/tcrm#106]
The test run goes fine, but while running example yasi.ini
its giving strange error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3.7\lib\configparser.py", line 788, in get
    value = d[option]
  File "C:\ProgramData\Anaconda3.7\lib\collections\__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\ProgramData\Anaconda3.7\lib\collections\__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tcrm.py", line 662, in <module>
    startup()
  File "tcrm.py", line 645, in startup
    main(configFile)
  File "tcrm.py", line 69, in wrap
    res = f(*args, **kwargs)
  File "tcrm.py", line 528, in main
    doDataProcessing(configFile)
  File "E:\Tropical_cyclone_Risk_Model\tcrmv2\Utilities\parallel.py", line 132, in wrap
    return f(*args, **kwargs)
  File "tcrm.py", line 255, in doDataProcessing
    dataProcess.processData()
  File "E:\Tropical_cyclone_Risk_Model\tcrmv2\DataProcess\DataProcess.py", line 178, in processData
    fn = config.get(source, 'filename')
  File "C:\ProgramData\Anaconda3.7\lib\configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'filename' in section: 'BDECK'

**Comment by makkulkarni** [comment]
Sorry, I was using wrong command , tcevent.py worked well, thanks
