### ISSUE TITLE
Having problems with compile.cmd

### ISSUE THREAD

**Issue by adgelt** [GeoscienceAustralia/tcrm#149]
I'm getting this issue of not finding the python311.dll in the folder but upon checking there is existing file. What could be the problem?

Looking for python311.dll
INFO: Building import library (arch=AMD64): "C:\Users\Gelo\libs\libpython311.a" (from C:\Users\Gelo\python311.dll)
error: [WinError 2] The system cannot find the file specified

![Screenshot 2024-05-26 231715](https://github.com/GeoscienceAustralia/tcrm/assets/158566237/178fb818-c20b-4b8d-9839-b71c70affaaa)

**Comment by wcarthur** [comment]
At present, we haven't built against Python 3.11 on Windows environment, so unsure what may be the cause. If you could provide additional info such as operating system, python version, what package manager you're using (e.g. conda, pip, virtualenv), we may be able to assist.

**Comment by adgelt** [comment]
> At present, we haven't built against Python 3.11 on Windows environment, so unsure what may be the cause. If you could provide additional info such as operating system, python version, what package manager you're using (e.g. conda, pip, virtualenv), we may be able to assist.

Hello, I'm using Windows 11 as OS, and tried installing the code using pip. What could be the problem?

**Comment by adgelt** [comment]
Hello, I'm using Windows 11 as OS, and tried installing the code using pip. What could be the problem?

**Comment by wcarthur** [comment]
This still uses an older build method for the FORTRAN extension packages (`wind.windmodels`, etc.), which is the likely culprit of the error you're seeing. I'll take a look at what's needed to update to the newer build systems: 

https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

**Comment by adgelt** [comment]
What versions of Python and other extension packages should I be using for the compile.cmd to work?

**Comment by wcarthur** [comment]
I've made an attempt to build on Windows x86-64 using MinGW-w64, Python 3.11, and can't get it to build, having tried a number of strategies. Some investigation suggested that there's an issue with MinGW-w64 interacting with the `python311.dll`. 

Rolling back to Python 3.10 is one suggested workaround. In the meantime, I'll continue to work on the package build for the next updates.

**Comment by adgelt** [comment]
What do you think is causing this error?
![image](https://github.com/user-attachments/assets/c8c43520-8832-47db-80a8-80e99d6a3f9f)

**Comment by wcarthur** [comment]
Since Python 3.11, the unittest package droopped support for namespace packages. This means the unittests will only discover tests if there's a `__init__.py` file in the directory. Presently there's no `__init__.py` file in the `tests` directory so the unitttest package cannot discover the suite of tests. 
There's two options:
1. create an empty file called `__init__.py` in the `tests` directory. This will enabpe `run_test_all.cmd` to discover the tests.
2. use `pytest -x` to run the tests (this will become the preferred option in future releases). `pytest` is listed in the `tcrmenv.yml` file as a dependency. 

Note: on Windows platforms, running the tests may generate `PermissionError` messages:
```
Traceback (most recent call last):
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\shutil.py", line 634, in _rmtree_unsafe
      os.unlink(fullname)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\blah\\AppData\\Local\\Temp\\tmp_xy80wsa\\windfield\\gust.001-00001.nc'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\weakref.py", line 590, in __call__
      return info.func(*info.args, **(info.kwargs or {}))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\tempfile.py", line 935, in _cleanup
      cls._rmtree(name, ignore_errors=ignore_errors)
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\tempfile.py", line 930, in _rmtree
      _shutil.rmtree(name, onexc=onexc)
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\shutil.py", line 808, in rmtree
      return _rmtree_unsafe(path, onexc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\shutil.py", line 631, in _rmtree_unsafe
      _rmtree_unsafe(fullname, onexc)
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\shutil.py", line 636, in _rmtree_unsafe
      onexc(os.unlink, fullname, err)
    File "C:\W10Dev\Anaconda3\envs\tcrm\Lib\tempfile.py", line 905, in onexc
      _os.unlink(path)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\blah\\AppData\\Local\\Temp\\tmp_xy80wsa\\windfield\\gust.001-00001.nc'
```
This is because the operating system tries to remove the temporary files while the process is still running. These errors can be ignored.

**Comment by adgelt** [comment]
after using the `pytest -x` this is what I got. I'm not sure on what it means.
![image](https://github.com/user-attachments/assets/4bb9d46b-9577-43fc-a926-9d7bc437c3dc)

**Comment by wcarthur** [comment]
Can you show the output of the following command:

`echo %PYTHONPATH%`

In my case, it lists the `tcrm` and `tcrm/Utilities` directories. Also check that `NumpyTestCase.py` exists in the `tests` directory.

**Comment by adgelt** [comment]
This is my `PYTHONPATH`
![image](https://github.com/user-attachments/assets/44e5c38a-39f1-4dca-b05b-a9bb649267bc)

`NumpyTestCase.py` is in my test directory.

Also tried the __init__.py and a lot of error popped out like this
![image](https://github.com/user-attachments/assets/22e0b5aa-11b9-4e92-a3ec-286323f1b464)

I found out that `array` is being imported from `scipy` in the `NumpyTestCase.py` which is supposed to be from `numpy`.

**Comment by adgelt** [comment]
Also, how do you resolve this type of warning?
![image](https://github.com/user-attachments/assets/e90e99d7-3da4-4478-87ef-2fe99ef40cbc)

**Comment by wcarthur** [comment]
> Also, how do you resolve this type of warning? ![image](https://private-user-images.githubusercontent.com/158566237/361313557-e90e99d7-3da4-4478-87ef-2fe99ef40cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDkzNjAsIm5iZiI6MTcyNDY0OTA2MCwicGF0aCI6Ii8xNTg1NjYyMzcvMzYxMzEzNTU3LWU5MGU5OWQ3LTNkYTQtNDQ3OC04N2VmLTJmZTk5ZWY0MGNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNTExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTM2OWNhOWZhNDk0OWJlOTU0MTg3ZmYzMjRiYmVjMGE0NjQyOTUwMDM2N2RiMDA5MWRlNzI1ZGYxYWVhNTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A-f7YMoposKeeaMupJ5etDIHyoyjXN9Joq93Y7iryeA)

THis can safely be ignored - see earlier comment about these FORTRAN extension packages.

**Comment by wcarthur** [comment]
> This is my `PYTHONPATH` ![image](https://private-user-images.githubusercontent.com/158566237/361299177-44e5c38a-39f1-4dca-b05b-a9bb649267bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDQ3NTMsIm5iZiI6MTcyNDY0NDQ1MywicGF0aCI6Ii8xNTg1NjYyMzcvMzYxMjk5MTc3LTQ0ZTVjMzhhLTM5ZjEtNGRjYS1iMDViLWE5YmI2NDkyNjdiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwMzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWIwNjBhYmQxNmZkYWNkMTNkZTdkMGJiZWVkZjc3YjcxNTVhNzYwYWYyMDQzYzcwNTYyZDE1YzcwOGI3NjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgZmfUnDzEDPXmwYVqUcyod4swpxu6om7jT5tFF_oNA)
> 
> `NumpyTestCase.py` is in my test directory.
> 
> Also tried the `__init__.py` and a lot of error popped out like this ![image](https://private-user-images.githubusercontent.com/158566237/361299871-22e0b5aa-11b9-4e92-a3ec-286323f1b464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDQ3NTMsIm5iZiI6MTcyNDY0NDQ1MywicGF0aCI6Ii8xNTg1NjYyMzcvMzYxMjk5ODcxLTIyZTBiNWFhLTExYjktNGU5Mi1hM2VjLTI4NjMyM2YxYjQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwMzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGRjYjgyZDNiZDdkOWQ3NTBhMTRmYTBiY2FiY2EwNmFkNzg0OTE2ZTMzNzRjMjliNjE2ZWI3YTM2ZWYzZDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SmFiAr-uuIGOAQS7PxkP5Tc_iuOYuleb3e8w83Pfm4Q)
> 
> I found out that `array` is being imported from `scipy` in the `NumpyTestCase.py` which is supposed to be from `numpy`.

I have no such issues (scipy 1.11.3) - may be worth checking scipy version installed
