### ISSUE TITLE
NoOptionError when running port_hedland.ini example

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#26]
Running port headland using tcrm.py, gives the following error, even though the gridLimit is set in the config file. And for some reason the output folders are not being created either.

> 11:59:13: File "D:\tcrm-2.0\DataProcess\CalcTrackDomain.py", line 49, in __init__
11:59:13: self.wf_domain = config.geteval('Region', 'gridLimit')
11:59:13: File "D:\tcrm-2.0\Utilities\config.py", line 256, in geteval
11:59:13: return self._get(section, eval, option)
11:59:13: File "D:\Python27\lib\ConfigParser.py", line 356, in _get
11:59:13: return conv(self.get(section, option))
11:59:13: File "D:\Python27\lib\ConfigParser.py", line 340, in get
11:59:13: raise NoOptionError(option, section)
11:59:13: NoOptionError: No option 'gridLimit' in section: 'Region'

**Comment by totalpanic** [comment]
Full main.log file:
2017-03-06 14:12:17: Started log file main.log (detail level INFO)
2017-03-06 14:12:17: Running tcrm.py (pid 4724)
2017-03-06 14:12:17: Starting TCRM
2017-03-06 14:12:17: Configuration file: example/port_headland.ini
2017-03-06 14:12:17: Output will be stored under output
2017-03-06 14:12:17: Checking availability of input data sets
2017-03-06 14:12:17: Running Data Processing
2017-03-06 14:12:17: Initialising DataProcess
2017-03-06 14:12:17: Running processData
2017-03-06 14:12:17: Loading IBTRACS dataset
2017-03-06 14:12:17: Processing input\Allstorms.ibtracs_wmo.v03r05.csv
2017-03-06 14:12:23: Processing data files:   12% complete
2017-03-06 14:12:23: Filtering input data by season: season > 1981
2017-03-06 14:12:26: Processing data files:   25% complete
2017-03-06 14:12:26: No max wind speed data
2017-03-06 14:12:26: No rmax data available
2017-03-06 14:12:26: Extracting longitudes and latitudes
2017-03-06 14:12:28: Extracting bearings
2017-03-06 14:12:28: Extracting the rate of bearing change
2017-03-06 14:12:28: Processing data files:   37% complete
2017-03-06 14:12:28: Extracting speeds
2017-03-06 14:12:29: Extracting the rate of speed change for each cyclone
2017-03-06 14:12:29: Extracting pressures
2017-03-06 14:12:30: Extracting the rate of pressure change
2017-03-06 14:12:30: Extracting maximum sustained wind speeds
2017-03-06 14:12:30: Extracting annual frequency of events
2017-03-06 14:12:30: Mean annual frequency:  86.7
2017-03-06 14:12:30: Standard deviation:  21.1
2017-03-06 14:12:30: Calculating annual distribution of observations
2017-03-06 14:12:30: Completed processData
2017-03-06 14:12:30: Processing data files:   50% complete
2017-03-06 14:12:30: Completed Data Processing
2017-03-06 14:12:30: Processing data files:  100% complete
2017-03-06 14:12:30: Running StatInterface
2017-03-06 14:12:30: Traceback (most recent call last):
2017-03-06 14:12:30: File "tcrm.py", line 634, in startup
2017-03-06 14:12:30: main(configFile)
2017-03-06 14:12:30: File "tcrm.py", line 53, in wrap
2017-03-06 14:12:30: res = f(*args, **kwargs)
2017-03-06 14:12:30: File "tcrm.py", line 516, in main
2017-03-06 14:12:30: doStatistics(configFile)
2017-03-06 14:12:30: File "D:\tcrm-2.0\Utilities\parallel.py", line 70, in wrap
2017-03-06 14:12:30: return f(*args, **kwargs)
2017-03-06 14:12:30: File "tcrm.py", line 349, in doStatistics
2017-03-06 14:12:30: CalcTD = CalcTrackDomain(configFile)
2017-03-06 14:12:30: File "D:\tcrm-2.0\DataProcess\CalcTrackDomain.py", line 49, in __init__
2017-03-06 14:12:30: self.wf_domain = config.geteval('Region', 'gridLimit')
2017-03-06 14:12:30: File "D:\tcrm-2.0\Utilities\config.py", line 256, in geteval
2017-03-06 14:12:30: return self._get(section, eval, option)
2017-03-06 14:12:30: File "D:\Python27\lib\ConfigParser.py", line 356, in _get
2017-03-06 14:12:30: return conv(self.get(section, option))
2017-03-06 14:12:30: File "D:\Python27\lib\ConfigParser.py", line 340, in get
2017-03-06 14:12:30: raise NoOptionError(option, section)
2017-03-06 14:12:30: NoOptionError: No option 'gridLimit' in section: 'Region'

**Comment by wcarthur** [comment]
Can I confirm you're using the v2.0 branch? The example config file for v2.0 refers to ibtracs v03r06, but the log file indicates v03r05, which is referenced in the master branch

**Comment by wcarthur** [comment]
@totalpanic I'm unable to replicate this with either the master branch or v2.0 branch example configuration files.

**Comment by totalpanic** [comment]
After some investigation it looks like python environment has cashed
configuration file somehow and was not picking up changes. After a complete
system reset the issue went away.



On 7 Mar 2017 8:17 AM, "Craig Arthur" <notifications@github.com> wrote:

@totalpanic <https://github.com/totalpanic> I'm unable to replicate this
with either the master branch or v2.0 branch example configuration files.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GeoscienceAustralia/tcrm/issues/26#issuecomment-284535481>,
or mute the thread
