### ISSUE TITLE
Travis.CI fails on import osgeo

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#28]
ImportError for osgeo:

> Failure: ImportError (No module named osgeo) ... ERROR
Failure: ImportError (No module named osgeo) ... ERROR
======================================================================
ERROR: Failure: ImportError (No module named osgeo)
----------------------------------------------------------------------
> Traceback (most recent call last):
  File "/home/travis/py/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/py/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/py/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/GeoscienceAustralia/tcrm/Evaluate/__init__.py", line 12, in <module>
    from Evaluate.pressureDistribution import PressureDistribution
  File "/home/travis/build/GeoscienceAustralia/tcrm/Evaluate/pressureDistribution.py", line 36, in <module>
    from PlotInterface.figures import QuantileFigure, saveFigure
  File "/home/travis/build/GeoscienceAustralia/tcrm/PlotInterface/figures.py", line 18, in <module>
    import wind.windmodels as windmodels
  File "/home/travis/build/GeoscienceAustralia/tcrm/wind/__init__.py", line 53, in <module>
    from ProcessMultipliers import processMultipliers as pM
  File "/home/travis/build/GeoscienceAustralia/tcrm/ProcessMultipliers/processMultipliers.py", line 45, in <module>
    from osgeo import osr, gdal
ImportError: No module named osgeo

Need to add osgeo to .travis.yml dependencies

**Comment by wcarthur** [comment]
This relates to v3.0 (now the `develop` branch)

**Comment by CEKrause** [comment]
Issue now in #51 (Closing this older one)
