### ISSUE TITLE
Check test suite

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/tcrm#37]
On gpd branch (but also true on others..)

Using `nosetests` to run the testing suite results in
- 173 tests run
- 0 errors

Using `python ./tests/run.py` (as documented in the TCRM user guide) results in
- 182 tests run
- 5 fails

The 5 failures are listed below. They are errors that should not have not been introduced by the gpd modifications - they are in tests for existing functionality. 

Not sure why `nosetests` does not pick up as many tests as the `run.py` script.

Error messages from failed tests:
```===================================================================
ERROR: test_generate_syn_mult_img (tests.test_processMultipliers.TestProcessMultipliers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/short/w85/cek156/tcrm_again/tests/test_processMultipliers.py", line 239, in test_generate_syn_mult_img
    pM.generate_syn_mult_img(136, -20, 2, dir_path, shape=(2, 4))
  File "/short/w85/cek156/tcrm_again/ProcessMultipliers/processMultipliers.py", line 98, in generate_syn_mult_img
    fill = value['fill']
TypeError: tuple indices must be integers, not str

===================================================================
ERROR: test_reprojectDataset_same_nc_img (tests.test_processMultipliers.TestProcessMultipliers)
Test a dataset is correctly reprojected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/short/w85/cek156/tcrm_again/tests/test_processMultipliers.py", line 174, in test_reprojectDataset_same_nc_img
    wg.saveGustToFile(None, result, f_nc.name)
  File "/short/w85/cek156/tcrm_again/wind/__init__.py", line 528, in saveGustToFile
    trackfileDate = flModDate(trackfile)
  File "/short/w85/cek156/tcrm_again/Utilities/files.py", line 291, in flModDate
    si = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, NoneType found

===================================================================
ERROR: test_xprocessMult_A (tests.test_processMultipliers.TestProcessMultipliers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/short/w85/cek156/tcrm_again/tests/test_processMultipliers.py", line 246, in test_xprocessMult_A
    pM.generate_syn_mult_img(136, -20, 2, dir_path, shape=(2, 4))
  File "/short/w85/cek156/tcrm_again/ProcessMultipliers/processMultipliers.py", line 98, in generate_syn_mult_img
    fill = value['fill']
TypeError: tuple indices must be integers, not str

===================================================================
ERROR: test_badinput (tests.test_columns.TestReadCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/short/w85/cek156/tcrm_again/tests/test_columns.py", line 28, in test_badinput
    self.configFile, self.badinput, self.source)
  File "/apps/python/2.7.6/lib/python2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/short/w85/cek156/tcrm_again/Utilities/columns.py", line 34, in colReadCSV
    delimiter = config.get(source, 'FieldDelimiter')
  File "/apps/python/2.7.6/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
NoSectionError: No section: 'TEST'

===================================================================
ERROR: test_readCSV (tests.test_columns.TestReadCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/short/w85/cek156/tcrm_again/tests/test_columns.py", line 33, in test_readCSV
    loadedData = columns.colReadCSV(self.configFile, self.inputFile, self.source)
  File "/short/w85/cek156/tcrm_again/Utilities/columns.py", line 34, in colReadCSV
    delimiter = config.get(source, 'FieldDelimiter')
  File "/apps/python/2.7.6/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
NoSectionError: No section: 'TEST'

----------------------------------------------------------------------
Ran 182 tests in 212.842s

FAILED (errors=5)
```

**Comment by wcarthur** [comment]
I'm unable to replicate the numbers above - I get 175 tests using both methods.

`nosetests` and `tests/run.py` execute in different ways, and I suspect (but haven't confirmed yet) that it'll be to do with the paths that they each search for tests. It does look like the multiplier tests were executed in `tests/run.py`...

**Comment by CEKrause** [comment]
I just re-checked; on the `develop` branch:
`nosetests` ran 175 tests, no errors
`python ./tests/run.py` ran 184 tests, 5 errors (the errors were the same as above)
