### ISSUE TITLE
AutoPlotHazard.plotCurves raises ProgrammingError

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#50]
Branch: `develop`

Executing the `AutoPlotHazard.plotCurves` method raises a `ProgrammingError` when trying to get the locations from the database.

```
2017-11-10 20:10:31: Plotting return period curves for locations within the model domain
2017-11-10 20:10:31: Cannot retrieve locations from tblLocations: Cannot operate on a closed database.
Traceback (most recent call last):
  File "/home/547/cxa547/tcrm/database/__init__.py", line 275, in getLocations
    cur = self.execute(("SELECT locId, locName, locLon, locLat "
ProgrammingError: Cannot operate on a closed database.
2017-11-10 20:10:31: Traceback (most recent call last):
2017-11-10 20:10:31: File "tcrm.py", line 670, in startup
2017-11-10 20:10:31: main(configFile)
2017-11-10 20:10:31: File "tcrm.py", line 86, in wrap
2017-11-10 20:10:31: res = f(*args, **kwargs)
2017-11-10 20:10:31: File "tcrm.py", line 583, in main
2017-11-10 20:10:31: doHazardPlotting(configFile)
2017-11-10 20:10:31: File "/home/547/cxa547/tcrm/Utilities/parallel.py", line 70, in wrap
2017-11-10 20:10:31: return f(*args, **kwargs)
2017-11-10 20:10:31: File "tcrm.py", line 463, in doHazardPlotting
2017-11-10 20:10:31: plotter.plotCurves()
2017-11-10 20:10:31: File "/home/547/cxa547/tcrm/PlotInterface/AutoPlotHazard.py", line 129, in plotCurves
2017-11-10 20:10:31: self.plotHazardCurves(self.inputFile, self.plotPath)
2017-11-10 20:10:31: File "/home/547/cxa547/tcrm/PlotInterface/AutoPlotHazard.py", line 197, in plotHazardCurves
2017-11-10 20:10:31: placeNames, placeID, placeLats, placeLons, locations = self.getLocations()
2017-11-10 20:10:31: File "/home/547/cxa547/tcrm/PlotInterface/AutoPlotHazard.py", line 171, in getLocations
2017-11-10 20:10:31: locations = self.db.getLocations()
2017-11-10 20:10:31: File "/home/547/cxa547/tcrm/database/__init__.py", line 275, in getLocations
2017-11-10 20:10:31: cur = self.execute(("SELECT locId, locName, locLon, locLat "
2017-11-10 20:10:31: ProgrammingError: Cannot operate on a closed database.
```

The database instance is created at line 89 in `PlotInterface/AutoPlotHazard.py`. 
Possible causes:
- database instance already exists and `HazardDatabase.getInstance` is returning a closed database rather than the existing instance which has an open connection
- instance is not actually creating an open connection

Options:
- check the database instance actually has an open connection

**Comment by wcarthur** [comment]
Closed with commit 8a70ada
