### ISSUE TITLE
"assert d2Vm < 0.0, AssertionError" occur when I run the model testing all the wind profiles, except for Holland

### ISSUE THREAD

**Issue by chavelyalbert** [GeoscienceAustralia/tcrm#62]
2019-01-28 21:11:37: Calculating wind fields for tracks in ./output/perfil_powell_500_sim/tracks/tracks.00032.nc
2019-01-28 21:11:53: Pressure deficit: 102.331543, RMW: 97884.208679
2019-01-28 21:11:53: Traceback (most recent call last):
2019-01-28 21:11:53: File "tcrm.py", line 634, in startup
2019-01-28 21:11:53: main(configFile)
2019-01-28 21:11:53: File "tcrm.py", line 53, in wrap
2019-01-28 21:11:53: res = f(*args, **kwargs)
2019-01-28 21:11:53: File "tcrm.py", line 526, in main
2019-01-28 21:11:53: doWindfieldCalculations(configFile)
2019-01-28 21:11:53: File "tcrm.py", line 212, in doWindfieldCalculations
2019-01-28 21:11:53: wind.run(configFile, status)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 848, in run
2019-01-28 21:11:53: wfg.dumpGustsFromTrackfiles(trackfiles, windfieldPath, timestepCallback)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 678, in dumpGustsFromTrackfiles
2019-01-28 21:11:53: timeStepCallback=timeStepCallback)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 483, in dumpGustsFromTracks
2019-01-28 21:11:53: for track, result in results:
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 419, in calculateExtremesFromTrack
2019-01-28 21:11:53: return track, wt.regionalExtremes(self.gridLimit, callback)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 279, in regionalExtremes
2019-01-28 21:11:53: Ux, Vy, P = self.localWindField(i)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/__init__.py", line 200, in localWindField
2019-01-28 21:11:53: Ux, Vy = windfield.field(R * 1000, theta, vFm, thetaFm,  thetaMax)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/windmodels.py", line 1038, in field
2019-01-28 21:11:53: V = self.velocity(R)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/windmodels.py", line 896, in velocity
2019-01-28 21:11:53: return self.profile.velocity(R)
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/windmodels.py", line 358, in velocity
2019-01-28 21:11:53: d2Vm = self.secondDerivative()
2019-01-28 21:11:53: File "/home/sosarica/Documents/tcrm-2.0.2/wind/windmodels.py", line 321, in secondDerivative
2019-01-28 21:11:53: assert d2Vm < 0.0
2019-01-28 21:11:53: AssertionError

**Comment by wcarthur** [comment]
We picked up an error in the WilloughbyWindProfile method, which was causing this error. Check if the latest fix (https://github.com/GeoscienceAustralia/tcrm/commit/99d78ea50e4b7a884a569805eff3f4bfe8dcfddd) does the trick. 

Any examples of this error when using radial profiles other than Willoughby would help us as well. Adding configuration files and log files (with the LogLevel set to DEBUG) would be great
